# Generated by Django 4.2.1 on 2023-06-06 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('number', models.IntegerField(editable=False, verbose_name='#')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('NOT_READY', 'not Ready'), ('READY', 'Ready'), ('DOING', 'Doing'), ('DONE', 'Done')], default='NOT_READY', max_length=40, verbose_name='status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('estimated_man_hour', models.TimeField(blank=True, null=True, verbose_name='estimated man hour')),
                ('actual_man_hour', models.TimeField(blank=True, null=True, verbose_name='actual man hour')),
                ('owner', models.TimeField(blank=True, null=True, verbose_name='owner')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
