# Generated by Django 4.2.1 on 2023-06-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_personal',
            field=models.BooleanField(default=False, editable=False, verbose_name='personal'),
        ),
    ]
