# Generated by Django 4.2.1 on 2023-05-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_admin',
            new_name='is_team_admin',
        ),
    ]
